### PR TITLE
cleanups by maddin200

### PR DESCRIPTION
**Pull request by jonsneyers**
3 small cleanups as proposed by @maddin200:

fixes https://github.com/libjxl/libjxl/issues/536, https://github.com/libjxl/libjxl/issues/515 and https://github.com/libjxl/libjxl/issues/514

### CODE REVIEW

**Comment by ziemek99** [comment]
#515 and #514 aren't linked to this PR.

**Comment by jonsneyers** [comment]
> #515 and #514 haven't been linked to this PR yet.

ah, thanks for noticing — I was hoping GitHub would figure it out itself, but looks like that only worked for the first one.

**Comment by ziemek99** [comment]
> ah, thanks for noticing — I was hoping GitHub would figure it out itself, but looks like that only worked for the first one.

You'd have to mention `fixes` before every PR number, like here: `fixes #536, fixes #515 and fixes #514`.

**Comment by ziemek99** [comment]
Oh, and by the way: what about automated dead code detection I mentioned [here](https://github.com/libjxl/libjxl/issues/515#issuecomment-910896157)?

**Comment by jonsneyers** [comment]
Do you have a specific tool you can recommend for that?

**Comment by ziemek99** [comment]
Unfortunately not, I thought *you* knew about one because you've developed more things for more time than me. Maybe other people know about such a tool?

**Review by ziemek99 — APPROVED** [review]

**Review by eustas — APPROVED** [review]

**Pull request merged**
