### PR TITLE
Reject decoding to JPEG when DCT coefficients are invalid

### PR DESCRIPTION
**Pull request by eustas**

### CODE REVIEW

**Comment by jonsneyers** [comment]
Have you tried measuring the decode speed impact of this extra check?
If this condition is only reached for malicious inputs and the only effect of not checking is that it produces garbage output, I don't know if we really need this check — depending on how much it costs to do the check.

**Comment by eustas** [comment]
On JPEG serialization stage some values cause out-of-bounds access.

I'll check performance change soon.

I expect minimal-to-almost-zero effect:
 - we read hot data we have just written
 - we just read/compare 2 (AVX512) vectors - unlike `di16`, `di16_full` is 2x longer

**Comment by eustas** [comment]
On AVX2 performance change is at noise level, as expected:
```
BEFORE
JPEG XL decoder v0.10.0 07203da0 [AVX2,SSE4,SSE2]
Reconstructed to JPEG.
3468 x 4624, geomean: 39.441 MP/s [38.03, 39.80], geomean: 11.448 MB/s [11.04, 11.55], 250 reps, 0 threads.

AFTER
JPEG XL decoder v0.10.0 1e567b3d [AVX2,SSE4,SSE2]
Reconstructed to JPEG.
3468 x 4624, geomean: 39.164 MP/s [37.28, 39.67], geomean: 11.368 MB/s [10.82, 11.51], 250 reps, 0 threads.

BEFORE
JPEG XL decoder v0.10.0 07203da0 [AVX2,SSE4,SSE2]
Reconstructed to JPEG.
3468 x 4624, geomean: 39.360 MP/s [37.39, 39.75], geomean: 11.424 MB/s [10.85, 11.54], 250 reps, 0 threads.

AFTER
JPEG XL decoder v0.10.0 1e567b3d [AVX2,SSE4,SSE2]
Reconstructed to JPEG.
3468 x 4624, geomean: 39.438 MP/s [37.98, 39.85], geomean: 11.447 MB/s [11.02, 11.57], 250 reps, 0 threads.

BEFORE
JPEG XL decoder v0.10.0 07203da0 [AVX2,SSE4,SSE2]
Reconstructed to JPEG.
3468 x 4624, geomean: 39.395 MP/s [37.09, 39.82], geomean: 11.435 MB/s [10.77, 11.56], 250 reps, 0 threads.

AFTER
JPEG XL decoder v0.10.0 1e567b3d [AVX2,SSE4,SSE2]
Reconstructed to JPEG.
3468 x 4624, geomean: 39.444 MP/s [37.31, 39.96], geomean: 11.449 MB/s [10.83, 11.60], 250 reps, 0 threads.
```

**Comment by eustas** [comment]
Gently ping.

**Review by mo271 — APPROVED** [review]

**Pull request merged**
