### PR TITLE
Clarify Safari support

### PR DESCRIPTION
**Pull request by sandstrom**
Clarify that Safari 17 supports JXL (not only the beta version).

### CODE REVIEW

**Review by mo271 — DISMISSED** [review]

**Comment by sandstrom** [comment]
CLA for a one-line comment removal? Are you kidding? 😄

**Comment by mo271** [comment]
> CLA for a one-line comment removal? Are you kidding? 😄

Unfortunately this is how it works, the cla bot does not check for the complexity of the commit.
In addition to that we have an authors check, but I'm happy to fix that for you.

Thanks for the contribution in any case. Please let us know if you are willing to fix this https://github.com/libjxl/libjxl/pull/2909/checks?check_run_id=18041006646 
(it should only take a few clicks)

**Comment by sandstrom** [comment]
Thanks @mo271!

**Comment by mo271** [comment]
> Thanks @mo271!

The Authors check is passing by now, @sandstrom. The only thing missing is the cla-check...

**Comment by sandstrom** [comment]
@mo271 I tried but it didn't work out. I have several different domains and Google accounts, and the email I use for Github isn't tied to any of the Google accounts.

I'd argue this falls outside the scope of a CLA, i.e. it's a trivial change where a CLA isn't needed.

**Review by eustas — APPROVED** [review]

**Pull request merged**
