### PR TITLE
add googletest to deps.sh

### LINKED ISSUE #3621: deps.sh doesn't download GTest
**Describe the bug**
CMake cannot find GTest after executing deps.sh to get dependencies

**To Reproduce**
Download source zip file, execute deps.sh and run cmake

**Expected behavior**
deps.sh installs all dependencies, cmake generating Makefiles

**Screenshots**
Exact output of cmake:
```CMake Error at /home/stefan/source/ffmpeg-build3/workspace/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR
  GTEST_MAIN_LIBRARY)
Call Stack (most recent call first):
  /home/stefan/source/ffmpeg-build3/workspace/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /home/stefan/source/ffmpeg-build3/workspace/share/cmake-3.27/Modules/FindGTest.cmake:270 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  third_party/testing.cmake:57 (find_package)
  CMakeLists.txt:358 (include)


-- Configuring incomplete, errors occurred!

Failed to Execute cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=/home/stefan/source/ffmpeg-build3/workspace -DENABLE_SHARED=off -DCMAKE_BUILD_TYPE=Release -DJPEGXL_ENABLE_BENCHMARK=OFF -DJPEGXL_ENABLE_DOXYGEN=OFF -DJPEGXL_ENABLE_MANPAGES=OFF -DJPEGXL_ENABLE_JPEGLI_LIBJPEG=OFF -DJPEGXL_ENABLE_JPEGLI=OFF -DJPEGXL_TEST_TOOLS=OFF -DJPEGXL_ENABLE_JNI=OFF .
```

**Environment**
 - OS: Linux Mint / Ubuntu 22.04 LTS
 - Compiler version: gcc 11.4.0
 - CPU type: x86_64
 - cjxl/djxl version string: 0.10.2

**Additional context**
I would like to include libjxl in an automated script to build a static ffmpeg. Therefore git should be avoided, I have no problem compiling libjxl with git submodules, I want a solution without git.
I am not sure for what GTest is needed and if there is any flag to disable the need for it.

### PR DESCRIPTION
**Pull request by mo271**
Fixes #3621

### CODE REVIEW

**Comment by eustas** [comment]
Isn't it better to use CMake `FetchContent`?

**Review by eustas — APPROVED** [review]

**Comment by mo271** [comment]
Not sure if we want this now

**Comment by sboukortt** [comment]
> Isn't it better to use CMake `FetchContent`?

I think we might have had this script so that we could create standalone source archives. Or was that not the reason?

**Comment by mo271** [comment]
I guess it also doesn't hurt to download it with this script...

**Pull request merged**
