### PR TITLE
Add swayimg to supported image viewers

### PR DESCRIPTION
**Pull request by roland-rollo**

### CODE REVIEW

**Review by mo271 — DISMISSED** [review]

**Comment by mo271** [comment]
Thanks for the contribution! Please sign the CLA and also add you name to the authors file!

**Comment by mo271** [comment]
it would be great, if you could sign the CLA, @roland-rollo !

**Comment by mo271** [comment]
> @mo271 Is now good?

Almost, you still need to add your name to the [AUTHORS](https://github.com/libjxl/libjxl/blob/main/AUTHORS) file. (The check is green right now, but only because I resolved a rebasing-conflict and the AUTHORS-check in the CI only checks the last commit..)
Make sure to keep the alphabetical order ..
Thanks in advance!

**Comment by mo271** [comment]
For your convenience, I have added your name from the commit to the AUTHORS files.

**Review by mo271 — APPROVED** [review]

**Comment by roland-rollo** [comment]
Jeez... I am so sorry you. I was reminded of it when I left work and wanted to add it now, but you overtook me. Thank you!

**Pull request merged**
