### PR TITLE
Fix a bunch of includes (detected by ClangTidy)

### PR DESCRIPTION
**Pull request by eustas**

### CODE REVIEW

**Review by mo271 — APPROVED** [review]

**Review by mo271 — APPROVED** [review]

**Comment by 1480c1** [comment]
I believe this change, specifically to `jxl/decode.h` is causing issues with FFmpeg, as the wrapper there relied on that header to include version.h implicitly. I believe @Traneptora is the most active with regard to the FFmpeg project and integration.

The error log I have is:
```c++
D:/clang/build/ffmpeg-git/libavcodec/libjxldec.c:217:103: error: too many arguments to function call, expected 3, have 4
  217 |     jret = JxlDecoderGetICCProfileSize(ctx->decoder, &ctx->jxl_pixfmt, JXL_COLOR_PROFILE_TARGET_DATA, &icc_len);
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                ^~~~~~~~
D:/clang/local64/include/jxl/decode.h:774:29: note: 'JxlDecoderGetICCProfileSize' declared here
  774 | JXL_EXPORT JxlDecoderStatus JxlDecoderGetICCProfileSize(
      |                             ^
  775 |     const JxlDecoder* dec, JxlColorProfileTarget target, size_t* size);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:/clang/build/ffmpeg-git/libavcodec/libjxldec.c:228:64: error: too many arguments to function call, expected 4, have 5
  227 |         jret = JxlDecoderGetColorAsICCProfile(ctx->decoder, &ctx->jxl_pixfmt, JXL_COLOR_PROFILE_TARGET_DATA,
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  228 |                                               ctx->iccp->data, icc_len);
      |                                                                ^~~~~~~
D:/clang/local64/include/jxl/decode.h:792:29: note: 'JxlDecoderGetColorAsICCProfile' declared here
  792 | JXL_EXPORT JxlDecoderStatus JxlDecoderGetColorAsICCProfile(
      |                             ^
  793 |     const JxlDecoder* dec, JxlColorProfileTarget target, uint8_t* icc_profile,
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  794 |     size_t size);
      |     ~~~~~~~~~~~
```

Which I believe is caused by the compatibility check with 0.7.0 and 0.8.0

**Comment by Traneptora** [comment]
`<jxl/version.h>` wasn't a public header so requiring you to include it now to get the API version info is an API break.

**Comment by Traneptora** [comment]
Note that the API docs don't reference version.h at all: https://libjxl.readthedocs.io/en/latest/api.html

**Comment by Traneptora** [comment]
@1480c1 https://github.com/libjxl/libjxl/issues/3177

**Comment by eustas** [comment]
Thanks for the heads-up. Will fix it soon.

**Pull request merged**
