### PR TITLE
disable installation of MIME file

### LINKED ISSUE #2183: Installation of plugin mime and thumbnailer files doesn't respect DATAROOTDIR
If the build is done on a Linux distribution where the DATADIR is in a location other than `${CMAKE_INSTALL_PREFIX}/share`, then the data files for plugins - the mime `packages/image-jxl.xml` file, and thumbnailers `jxl.thumbnailer` file in particular - will be installed in the wrong location.

An example is in [Exherbo](https://www.exherbo.org/), where our standard cmake path setup uses `-DCMAKE_INSTALL_PREFIX:PATH=/usr/x86_64-pc-linux-gnu -DCMAKE_INSTALL_DATAROOTDIR:PATH=/usr/share/`. The data files get installed to `/usr/x86_64-pc-linux-gnu/share/` instead of the desired `/usr/share/`.

The fix is that these files should be installed using the [GNUInstallDirs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html#module:GNUInstallDirs) `${CMAKE_INSTALL_DATADIR}` variable instead of a hardcoded `share` path.

### PR DESCRIPTION
**Pull request by mo271**
fixes #2183

### CODE REVIEW

**Comment by andrius4669** [comment]
depends on distro, eg https://packages.debian.org/bullseye/shared-mime-info and https://packages.ubuntu.com/jammy/shared-mime-info

**Comment by kmilos** [comment]
> depends on distro, eg https://packages.debian.org/bullseye/shared-mime-info and https://packages.ubuntu.com/jammy/shared-mime-info

libjxl is not available (and is unlikely to be) on bullseye nor jammy, so no problem?

**Comment by andrius4669** [comment]
you can still build it on these systems

**Comment by kmilos** [comment]
The readme has instructions how to add it manually.

**Comment by kmilos** [comment]
I guess the alternative would be to default the option to OFF and have it enabled explicitly in deb recipes for these older systems...

**Comment by mo271** [comment]
In light of the issue mentioned (#2183), I think it would be best to merge this as is.

**Review by veluca93 — APPROVED** [review]

**Review by eustas — APPROVED** [review]

**Pull request merged**
