### PR TITLE
Allow delta palette in >8-bit images.

### PR DESCRIPTION
**Pull request by iulia-m-comsa**
tools/benchmark_xl --input='jyrki31-depth16/*.png' --codec=jxl:m:p0:lp:9 --error_pnorm=1 
benchmark_xl v0.7.0 e0f4c38 [AVX2,SSE4,Scalar]
6 cores, 61 tasks, 6 threads, 0 inner threads

Before:
```
Encoding         kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs
---------------------------------------------------------------------------------------------------------------
jxl:m:p0:lp:9      16443  5346967    2.6013328   0.077   8.516   2.28837752   0.53577100  1.393718668969      0
Aggregate:         16443  5346967    2.6013328   0.077   8.516   2.28837752   0.53577100  1.393718668969      0
```
After:
```
Encoding         kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs
---------------------------------------------------------------------------------------------------------------
jxl:m:p0:lp:9      16443  5363900    2.6095708   0.055   8.615   2.26338792   0.53316436  1.391330134341      0
Aggregate:         16443  5363900    2.6095708   0.055   8.615   2.26338792   0.53316436  1.391330134341      0
```

Co-authored-by: Jyrki Alakuijala <jyrki@google.com>

### CODE REVIEW

**Comment by jonsneyers** [comment]
What is "Before" here? Because lossy-palette in > 8-bit wasn't supported there yet, right?

**Comment by iulia-m-comsa** [comment]
> What is "Before" here? Because lossy-palette in > 8-bit wasn't supported there yet, right?

"Before" is current result on 16-bit images (the "jyrki31" set converted to 16-bit), which is indeed without the delta palette.

**Comment by jonsneyers** [comment]
> > What is "Before" here? Because lossy-palette in > 8-bit wasn't supported there yet, right?
> 
> "Before" is current result on 16-bit images (the "jyrki31" set converted to 16-bit), which is indeed without the delta palette.

But how are the results so close to the new results?
Also: maybe it would be good to try it on 10/12-bit content that actually has that bitdepth, as opposed to 8-bit images converted to 16-bit (which keep having only 256 distinct values per channel).

**Review by veluca93 — APPROVED** [review]

**Comment by iulia-m-comsa** [comment]
> > > What is "Before" here? Because lossy-palette in > 8-bit wasn't supported there yet, right?
> > 
> > 
> > "Before" is current result on 16-bit images (the "jyrki31" set converted to 16-bit), which is indeed without the delta palette.
> 
> But how are the results so close to the new results?
> Also: maybe it would be good to try it on 10/12-bit content that actually has that bitdepth, as opposed to 8-bit images converted to 16-bit (which keep having only 256 distinct values per channel).

Most images in the set don't actually end up using any deltas - only a couple of them do, in both the 8-bit and 16-bit versions. This is why the improvement is very small. I've also tried 10/12-bit content, there is no difference there. 
We also want to make other further improvements to the delta palette, this is just one more iteration.

**Review by jonsneyers — APPROVED** [review]

**Review by jyrkialakuijala — COMMENTED** [review]
LGTM

**Pull request merged**
