### PR TITLE
Unblock commit queue.

### PR DESCRIPTION
**Pull request by eustas**
See #910.

### CODE REVIEW

**Review by veluca93 — APPROVED** [review]

**Comment by eustas** [comment]
Added a real fix. PTAL

**Comment by veluca93** [comment]
> Added a real fix. PTAL

Ehhh, this is not really a real fix - it just disables cross-compiling things that depends on qt5...

**Review by lvandeve — APPROVED** [review]

**Comment by veluca93** [comment]
Let's maybe put a TODO to once again test viewers on i386/armhf at some point?

**Comment by eustas** [comment]
Oh, indeed, it reports "Qt5 was not found."
I'll put back the todo.

**Pull request merged**
