### PR TITLE
Round towards zero, not upwards

### PR DESCRIPTION
**Pull request by eustas**
That makes difference for negative input values, and we have those indeed.

TEST ColorManagementTest.XYBProfile:
```
BEFORE
(1.000000, 0.312500, 0.625000) -> ( 0.012363, 0.649471, 0.712981) -> (0.638119, 0.768324, 0.512553) -> ( 0.999145,  0.312813,  0.625123)    0.000855
(0.000000, 1.000000, 0.312500) -> (-0.015018, 0.725378, 0.568997) -> (0.008456, 0.858122, 0.182245) -> ( 0.000201,  0.999641,  0.312647)    0.000359
(0.687500, 1.000000, 0.000000) -> (-0.004086, 0.788682, 0.565756) -> (0.259865, 0.933010, 0.082285) -> ( 0.687048,  0.999840,  0.000450)    0.000450

AFTER
(1.000000, 0.312500, 0.625000) -> ( 0.012363, 0.649471, 0.712981) -> (0.638119, 0.768324, 0.512553) -> ( 0.999139,  0.312732,  0.625010)    0.000861
(0.000000, 1.000000, 0.375000) -> (-0.014948, 0.727467, 0.590242) -> (0.010085, 0.860593, 0.211021) -> ( 0.000161,  0.999574,  0.375014)    0.000426
(0.000000, 0.687500, 0.875000) -> (-0.012349, 0.649920, 0.700129) -> (0.069831, 0.768856, 0.492572) -> ( 0.000630,  0.687140,  0.874492)    0.000508
```

### CODE REVIEW

**Comment by eustas** [comment]
NB: this will require updating golden ICC profiles in conformance tests!

**Review by sboukortt — DISMISSED** [review]

**Comment by sboukortt** [comment]
(How did the force-push not “dismiss stale review”?)

**Comment by eustas** [comment]
Because it is no-diff, just rebase =) Anyways, pushed to re-trigger actions, to start debugging, what is wrong.

**Comment by sboukortt** [comment]
I thought I’d had stale reviews from no-diff rebases, but maybe I’ve been doing them wrong.

**Comment by eustas** [comment]
"Original" ICC:
```
00000000: 00 00 02 18 6a 78 6c 20  ....jxl 
00000008: 04 40 00 00 6d 6e 74 72  .@..mntr
00000010: 52 47 42 20 58 59 5a 20  RGB XYZ 
00000018: 07 e3 00 0c 00 01 00 00  ........
00000020: 00 00 00 00 61 63 73 70  ....acsp
00000028: 41 50 50 4c 00 00 00 00  APPL....
00000030: 00 00 00 00 00 00 00 00  ........
00000038: 00 00 00 00 00 00 00 00  ........
00000040: 00 00 00 01 00 00 f6 d6  ........
00000048: 00 01 00 00 00 00 d3 2d  .......-
00000050: 6a 78 6c 20 02 b9 f9 01  jxl ....
00000058: 40 73 3a 6f f0 ff 03 f4  @s:o....
00000060: f0 f7 0a 2b 00 00 00 00  ...+....
00000068: 00 00 00 00 00 00 00 00  ........
00000070: 00 00 00 00 00 00 00 00  ........
00000078: 00 00 00 00 00 00 00 00  ........
00000080: 00 00 00 0b 64 65 73 63  ....desc
00000088: 00 00 01 08 00 00 00 44  .......D
00000090: 63 70 72 74 00 00 01 4c  cprt...L
00000098: 00 00 00 24 77 74 70 74  ...$wtpt
000000a0: 00 00 01 70 00 00 00 14  ...p....
000000a8: 63 68 61 64 00 00 01 84  chad....
000000b0: 00 00 00 2c 63 69 63 70  ...,cicp
000000b8: 00 00 01 b0 00 00 00 0c  ........
000000c0: 72 58 59 5a 00 00 01 bc  rXYZ....
000000c8: 00 00 00 14 67 58 59 5a  ....gXYZ
000000d0: 00 00 01 d0 00 00 00 14  ........
000000d8: 62 58 59 5a 00 00 01 e4  bXYZ....
000000e0: 00 00 00 14 72 54 52 43  ....rTRC
000000e8: 00 00 01 f8 00 00 00 20  ....... 
000000f0: 67 54 52 43 00 00 01 f8  gTRC....
000000f8: 00 00 00 20 62 54 52 43  ... bTRC
00000100: 00 00 01 f8 00 00 00 20  ....... 
00000108: 6d 6c 75 63 00 00 00 00  mluc....
00000110: 00 00 00 01 00 00 00 0c  ........
00000118: 65 6e 55 53 00 00 00 26  enUS...&
00000120: 00 00 00 1c 00 52 00 47  .....R.G
00000128: 00 42 00 5f 00 44 00 36  .B._.D.6
00000130: 00 35 00 5f 00 53 00 52  .5._.S.R
00000138: 00 47 00 5f 00 52 00 65  .G._.R.e
00000140: 00 6c 00 5f 00 53 00 52  .l._.S.R
00000148: 00 47 00 00 6d 6c 75 63  .G..mluc
00000150: 00 00 00 00 00 00 00 01  ........
00000158: 00 00 00 0c 65 6e 55 53  ....enUS
00000160: 00 00 00 06 00 00 00 1c  ........
00000168: 00 43 00 43 00 30 00 00  .C.C.0..
00000170: 58 59 5a 20 00 00 00 00  XYZ ....
00000178: 00 00 f6 d6 00 01 00 00  ........
00000180: 00 00 d3 2d 73 66 33 32  ...-sf32
00000188: 00 00 00 00 00 01 0c 40  .......@
00000190: 00 00 05 dd ff ff f3 2a  .......*
00000198: 00 00 07 92 00 00 fd 90  ........
000001a0: ff ff fb a3 ff ff fd a3  ........
000001a8: 00 00 03 db 00 00 c0 81  ........
000001b0: 63 69 63 70 00 00 00 00  cicp....
000001b8: 01 0d 00 01 58 59 5a 20  ....XYZ 
000001c0: 00 00 00 00 00 00 6f 9f  ......o.
000001c8: 00 00 38 f5 00 00 03 90  ..8.....
000001d0: 58 59 5a 20 00 00 00 00  XYZ ....
000001d8: 00 00 62 96 00 00 b7 87  ..b.....
000001e0: 00 00 18 db 58 59 5a 20  ....XYZ 
000001e8: 00 00 00 00 00 00 24 a2  ......$.
000001f0: 00 00 0f 85 00 00 b6 d6  ........
000001f8: 70 61 72 61 00 00 00 00  para....
00000200: 00 03 00 00 00 02 66 66  ......ff
00000208: 00 00 f2 a7 00 00 0d 59  .......Y
00000210: 00 00 13 d0 00 00 0a 5b  .......[
```

New ICC:
```
00000000: 00 00 02 18 6a 78 6c 20  ....jxl 
00000008: 04 40 00 00 6d 6e 74 72  .@..mntr
00000010: 52 47 42 20 58 59 5a 20  RGB XYZ 
00000018: 07 e3 00 0c 00 01 00 00  ........
00000020: 00 00 00 00 61 63 73 70  ....acsp
00000028: 41 50 50 4c 00 00 00 00  APPL....
00000030: 00 00 00 00 00 00 00 00  ........
00000038: 00 00 00 00 00 00 00 00  ........
00000040: 00 00 00 01 00 00 f6 d6  ........
00000048: 00 01 00 00 00 00 d3 2d  .......-
00000050: 6a 78 6c 20[42 5b 41 0c  jxl B[A.
00000058: 0a 82 85 63 9e b2 34 ef  ...c..4.
00000060: 7c 6d a6 47]00 00 00 00  |m.G....
00000068: 00 00 00 00 00 00 00 00  ........
00000070: 00 00 00 00 00 00 00 00  ........
00000078: 00 00 00 00 00 00 00 00  ........
00000080: 00 00 00 0b 64 65 73 63  ....desc
00000088: 00 00 01 08 00 00 00 44  .......D
00000090: 63 70 72 74 00 00 01 4c  cprt...L
00000098: 00 00 00 24 77 74 70 74  ...$wtpt
000000a0: 00 00 01 70 00 00 00 14  ...p....
000000a8: 63 68 61 64 00 00 01 84  chad....
000000b0: 00 00 00 2c 63 69 63 70  ...,cicp
000000b8: 00 00 01 b0 00 00 00 0c  ........
000000c0: 72 58 59 5a 00 00 01 bc  rXYZ....
000000c8: 00 00 00 14 67 58 59 5a  ....gXYZ
000000d0: 00 00 01 d0 00 00 00 14  ........
000000d8: 62 58 59 5a 00 00 01 e4  bXYZ....
000000e0: 00 00 00 14 72 54 52 43  ....rTRC
000000e8: 00 00 01 f8 00 00 00 20  ....... 
000000f0: 67 54 52 43 00 00 01 f8  gTRC....
000000f8: 00 00 00 20 62 54 52 43  ... bTRC
00000100: 00 00 01 f8 00 00 00 20  ....... 
00000108: 6d 6c 75 63 00 00 00 00  mluc....
00000110: 00 00 00 01 00 00 00 0c  ........
00000118: 65 6e 55 53 00 00 00 26  enUS...&
00000120: 00 00 00 1c 00 52 00 47  .....R.G
00000128: 00 42 00 5f 00 44 00 36  .B._.D.6
00000130: 00 35 00 5f 00 53 00 52  .5._.S.R
00000138: 00 47 00 5f 00 52 00 65  .G._.R.e
00000140: 00 6c 00 5f 00 53 00 52  .l._.S.R
00000148: 00 47 00 00 6d 6c 75 63  .G..mluc
00000150: 00 00 00 00 00 00 00 01  ........
00000158: 00 00 00 0c 65 6e 55 53  ....enUS
00000160: 00 00 00 06 00 00 00 1c  ........
00000168: 00 43 00 43 00 30 00 00  .C.C.0..
00000170: 58 59 5a 20 00 00 00 00  XYZ ....
00000178: 00 00 f6 d6 00 01 00 00  ........
00000180: 00 00 d3 2d 73 66 33 32  ...-sf32
00000188: 00 00 00 00 00 01 0c 40  .......@
00000190: 00 00 05 dd ff ff f3[29] .......)
00000198: 00 00 07 92 00 00 fd 90  ........
000001a0: ff ff fb[a2]ff ff fd[a2] ........
000001a8: 00 00 03 db 00 00 c0 81  ........
000001b0: 63 69 63 70 00 00 00 00  cicp....
000001b8: 01 0d 00 01 58 59 5a 20  ....XYZ 
000001c0: 00 00 00 00 00 00 6f 9f  ......o.
000001c8: 00 00 38 f5 00 00 03 90  ..8.....
000001d0: 58 59 5a 20 00 00 00 00  XYZ ....
000001d8: 00 00 62 96 00 00 b7 87  ..b.....
000001e0: 00 00 18 db 58 59 5a 20  ....XYZ 
000001e8: 00 00 00 00 00 00 24 a2  ......$.
000001f0: 00 00 0f 85 00 00 b6 d6  ........
000001f8: 70 61 72 61 00 00 00 00  para....
00000200: 00 03 00 00 00 02 66 66  ......ff
00000208: 00 00 f2 a7 00 00 0d 59  .......Y
00000210: 00 00 13 d0 00 00 0a 5b  .......[
```

Difference offsets: 0x54 - 0x63, 0x197, 0x1A3, 0x1A7 (marked with square brackets). The last three ones are obvious due to change in rounding. Going to investigate why `jxl` chunk is so different.

**Comment by eustas** [comment]
16-byte range is MD5 checksum.

Overall, this profile is forged by libjxl. 'original.icc' file name is somewhat misleading in conformance tests. Going to rebaseline it (upload 1 file and update a bunch of hashes)

**Review by szabadka — APPROVED** [review]

**Pull request merged**
