### PR TITLE
Elevate C++ standard to 17

### PR DESCRIPTION
**Pull request by cagelight**
I would like to propose this pull request to allow more modern C++ to be used in the code base. I feel it has been long enough since 2017 that this should not pose any issues, and it would allow issues like #1038 to be easily fixed.

### CODE REVIEW

**Comment by malaterre** [comment]
In case this issue is ever considered. I'd like to also suggest the following approach as was done in related highway project:

* https://github.com/google/highway/issues/486

So the patch would be more like this:

* https://github.com/google/highway/commit/3ddf82d0b25b045ec5790ac9447c67dd93b98ab9

Thanks for consideration.

**Comment by malaterre** [comment]
One last comment, the following would also need to be addressed for consistency. Something like:

```
Index: libjxl/lib/CMakeLists.txt
===================================================================
--- libjxl.orig/lib/CMakeLists.txt
+++ libjxl/lib/CMakeLists.txt
@@ -39,7 +39,7 @@ set(JPEGXL_INTERNAL_FLAGS
   # WARN_FLAGS
   -Wall
   -Wextra
-  -Wc++11-compat
+  -Wc++17-compat
   -Warray-bounds
   -Wformat-security
   -Wimplicit-fallthrough
```

**Comment by hohMiyazawa** [comment]
The default ``gcc`` version in Ubuntu 18.04 long term support is ``v7.4.0``. Full support for c++17 is from ``gcc 8`` and on.

**Comment by EwoutH** [comment]
I support updating to C++17.

> The default `gcc` version in Ubuntu 18.04 long term support is `v7.4.0`. Full support for c++17 is from `gcc 8` and on.

There will always be cases that aren't covered when updating a requirement. Because Ubuntu 20.04 LTS is available and GCC 8 to 11 can be installed easily on Ubuntu 18.04, I don't think this is a blocking isssue.
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt install gcc-11 g++-11
```

**Comment by eustas** [comment]
Shadowed by #3590

**Pull request closed without merging**
