### PR TITLE
WIP candidate replacement for cache_aligned.cc

### PR DESCRIPTION
**Pull request by veluca93**
- [ ] depends on: #1100

### CODE REVIEW

**Comment by mo271** [comment]
blocked by #1100

**Comment by eustas** [comment]
Hi. Why it depends on c++17?
https://en.cppreference.com/w/c/memory/aligned_alloc says `since C11`.

**Comment by veluca93** [comment]
> Hi. Why it depends on c++17? https://en.cppreference.com/w/c/memory/aligned_alloc says `since C11`.

That's C11, not C++11, right?

**Comment by eustas** [comment]
True: https://en.cppreference.com/w/cpp/memory/c/aligned_alloc

What about `std::aligned_storage`? Does `new` initialize it? (and is it possible to `delete` it after we "forget" its true type).

**Comment by veluca93** [comment]
I'm honestly not sure... I don't really remember what I was going for with this PR either.

**Comment by eustas** [comment]
Then I'll just add a TODO to `memory_manager` that we could switch to aligned_alloc after c++17 is a mainline.

**Comment by eustas** [comment]
(nope, doesn't fit external memory manager API)

**Pull request closed without merging**
