### PR TITLE
fixing animations with cropped frames

### PR DESCRIPTION
**Pull request by mo271**

### CODE REVIEW

**Comment by jonsneyers** [comment]
Does the old cjxl still work after this?

**Comment by mo271** [comment]
> Does the old cjxl still work after this?

For gif it seems to work. For apng, I'm having a file where I see new artifacts after the change. Will look into fixing this...

**Comment by mo271** [comment]
> Does the old cjxl still work after this?

Now cjxl gives byte-identical files for both gifs and apngs before and after this change.

**Review by veluca93 — APPROVED** [review]

**Comment by sboukortt** [comment]
I seem to be getting 0-byte JXL files from single-frame PNG files using `cjxl_ng` starting with this change, do you also observe this behavior?

**Comment by mo271** [comment]
> I seem to be getting 0-byte JXL files from single-frame PNG files using `cjxl_ng` starting with this change, do you also observe this behavior?

This was not intended. Will look into it...

**Pull request merged**
