### PR TITLE
New AR control field heuristics.

### PR DESCRIPTION
**Pull request by szabadka**
The new algorithm bases the EPF strength decision on the actual reconstructed images filtered with the given EPF strength.

Benchmark results:
```
Encoding      kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2   PSNR        pnorm       BPP*pnorm   QABPP   Bugs
----------------------------------------------------------------------------------------------------------------------------------------
BEFORE:
jxl:d0.1        20795 17960414    6.9092543   5.755  43.438   0.35676469  95.37045907  55.92   0.11743201  0.811367620746   6.909      0
jxl:d0.25       20795 11211481    4.3129837   6.651  47.980   0.47188711  93.95812476  51.27   0.19471022  0.839782033058   4.323      0
jxl:d0.5        20795  7343631    2.8250470   7.426  52.544   0.77713256  91.44634906  47.21   0.33192928  0.937715835158   2.911      0
jxl:d1          20795  4677692    1.7994777   8.299  54.165   1.34254171  86.90547291  43.27   0.56234123  1.011920474406   2.522      0
jxl:d2          20795  2886906    1.1105739   8.834  54.788   2.41345744  78.64070212  39.51   0.96381616  1.070389106583   2.822      0
jxl:d4          20795  1697421    0.6529868   8.108  42.320   4.09606455  65.00253202  36.14   1.60465567  1.047818979599   2.800      0
jxl:d8          20795  1000234    0.3847835   8.244  40.996   6.58003645  45.10259245  33.21   2.54751704  0.980242539117   2.576      0
Aggregate:      20795  4437904    1.7072329   7.546  47.724   1.41620256  77.25130756  43.13   0.55786685  0.952408666679   3.322      0
AFTER:
jxl:d0.1        20795 17960541    6.9093032   5.407  42.890   0.35676469  95.37045907  55.92   0.11743201  0.811373358013   6.909      0
jxl:d0.25       20795 11211603    4.3130307   6.196  47.317   0.47188711  93.95812476  51.27   0.19471022  0.839791171316   4.323      0
jxl:d0.5        20795  7343761    2.8250970   7.016  51.698   0.77713256  91.44634906  47.21   0.33192928  0.937732434992   2.911      0
jxl:d1          20795  4663158    1.7938865   5.824  52.251   1.34223458  86.92083387  43.31   0.56028046  1.005079568151   2.512      0
jxl:d2          20795  2883258    1.1091706   6.066  52.041   2.40615718  78.70689283  39.63   0.95343141  1.057518069706   2.807      0
jxl:d4          20795  1720412    0.6618313   5.059  40.640   4.02415306  65.76256057  36.37   1.56497555  1.035749795869   2.791      0
jxl:d8          20795  1031404    0.3967744   5.181  41.609   6.47993724  47.18952937  33.48   2.47074579  0.980328683551   2.621      0
Aggregate:      20795  4463209    1.7169674   5.788  46.672   1.40887758  77.89265621  43.25   0.55230474  0.948289250653   3.324      0
```

Images before:
https://storage.googleapis.com/jxl-quality/eval/szabadka/jyrki_split_2024-03-23/26e522d7/base/index.jxl_d2.html

Images after:
https://storage.googleapis.com/jxl-quality/eval/szabadka/jyrki_split_2024-03-23/ddd30717/base/index.jxl_d2.html

### CODE REVIEW

**Review by jyrkialakuijala — DISMISSED** [review]
why did decoding get slower, too

**Comment by szabadka** [comment]
Maybe I was using too many threads.

Here is a benchmark with --num_threads=8

before:

```
Encoding      kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2   PSNR        pnorm       BPP*pnorm   QABPP   Bugs
----------------------------------------------------------------------------------------------------------------------------------------
jxl:d0.1        20795 17960414    6.9092543   5.667  43.639   0.35676469  95.37045907  55.92   0.11743201  0.811367620746   6.909      0
jxl:d0.25       20795 11211481    4.3129837   6.444  48.834   0.47188711  93.95812476  51.27   0.19471022  0.839782033058   4.323      0
jxl:d0.5        20795  7343631    2.8250470   7.257  53.099   0.77713256  91.44634906  47.21   0.33192928  0.937715835158   2.911      0
jxl:d1          20795  4677692    1.7994777   8.120  53.766   1.34254171  86.90547291  43.27   0.56234123  1.011920474406   2.522      0
jxl:d2          20795  2886906    1.1105739   8.623  53.864   2.41345744  78.64070212  39.51   0.96381616  1.070389106583   2.822      0
jxl:d4          20795  1697421    0.6529868   7.798  41.439   4.09606455  65.00253202  36.14   1.60465567  1.047818979599   2.800      0
jxl:d8          20795  1000234    0.3847835   7.994  40.631   6.58003645  45.10259245  33.21   2.54751704  0.980242539117   2.576      0
Aggregate:      20795  4437904    1.7072329   7.348  47.577   1.41620256  77.25130756  43.13   0.55786685  0.952408666679   3.322      0
```

after:
```
Encoding      kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2   PSNR        pnorm       BPP*pnorm   QABPP   Bugs
----------------------------------------------------------------------------------------------------------------------------------------
jxl:d0.1        20795 17960541    6.9093032   5.017  39.054   0.35676469  95.37045907  55.92   0.11743201  0.811373358013   6.909      0
jxl:d0.25       20795 11211603    4.3130307   5.695  43.559   0.47188711  93.95812476  51.27   0.19471022  0.839791171316   4.323      0
jxl:d0.5        20795  7343761    2.8250970   6.435  46.917   0.77713256  91.44634906  47.21   0.33192928  0.937732434992   2.911      0
jxl:d1          20795  4661156    1.7931164   5.278  46.073   1.34183133  86.91182193  43.35   0.55814469  1.000818382521   2.514      0
jxl:d2          20795  2879199    1.1076091   5.412  46.431   2.41376322  78.59705840  39.64   0.95394965  1.056603315771   2.810      0
jxl:d4          20795  1717143    0.6605737   4.583  34.284   4.04711626  65.56610271  36.38   1.56647308  1.034770965746   2.802      0
jxl:d8          20795  1026482    0.3948809   4.674  35.303   6.49569992  46.74880752  33.48   2.47294840  0.976520194289   2.614      0
Aggregate:      20795  4457778    1.7148780   5.267  41.349   1.41108829  77.73841160  43.25   0.55219205  0.946942011366   3.326      0
```

It is still slower but the difference is less. Maybe we use filtering more often now.

**Comment by jyrkialakuijala** [comment]
Let's find a way not to use filtering more often

**Comment by jonsneyers** [comment]
While according to the metrics it seems to be an overall improvement in quality/bpp, this seems to be a substantial encoder slowdown too (going from 8 Mpx/s to 5 Mpx/s). Can this slowdown be mitigated?

How are other efforts than the default effort affected?

**Comment by szabadka** [comment]
Added a 0.93 factor bias for epf strength 0. Now single thread decoding speed is about the same with 8 threads it is about 2% slower.

**Comment by szabadka** [comment]
> While according to the metrics it seems to be an overall improvement in quality/bpp, this seems to be a substantial encoder slowdown too (going from 8 Mpx/s to 5 Mpx/s). Can this slowdown be mitigated?
> 
> How are other efforts than the default effort affected?

The encoder slowdown is expected, since we decode the image 3 times inside the encoder now. Since decode is about 10x faster than encode, this adds about 30% to the encode time.

Only efforts 6 and above are affected. Benchmark on effort 6:

```
Encoding       kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2   PSNR        pnorm       BPP*pnorm   QABPP   Bugs
-----------------------------------------------------------------------------------------------------------------------------------------
BEFORE:
jxl:d0.1:6       20795 17859284    6.8703503   7.291  43.326   0.35909517  95.34837403  55.69   0.11899012  0.817503785154   6.872      0
jxl:d0.25:6      20795 11169872    4.2969770   8.576  47.963   0.48839340  93.88022760  51.06   0.19726629  0.847648706539   4.318      0
jxl:d0.5:6       20795  7279888    2.8005255  10.268  53.796   0.78525682  91.27818777  47.02   0.33551277  0.939612059770   2.887      0
jxl:d1:6         20795  4610232    1.7735262  11.908  53.817   1.37545408  86.55469305  43.11   0.57261271  1.015543669730   2.537      0
jxl:d2:6         20795  2832017    1.0894585  13.203  54.800   2.45583204  78.27084045  39.38   0.98143039  1.069227674344   2.806      0
jxl:d4:6         20795  1685543    0.6484174  14.146  43.978   4.09820795  64.81258457  36.09   1.61032213  1.044160913279   2.762      0
jxl:d8:6         20795   997515    0.3837375  14.713  43.939   6.58636036  44.85540890  33.16   2.55613817  0.980886135250   2.563      0
Aggregate:       20795  4399054    1.6922873  11.119  48.564   1.43543055  77.02999816  43.00   0.56428516  0.954932613117   3.306      0
AFTER:
jxl:d0.1:6       20795 17859412    6.8703995   6.837  42.757   0.35909517  95.34837403  55.69   0.11899012  0.817509644318   6.872      0
jxl:d0.25:6      20795 11170005    4.2970282   8.008  47.479   0.48839340  93.88022760  51.06   0.19726629  0.847658799517   4.318      0
jxl:d0.5:6       20795  7280015    2.8005744   9.501  51.800   0.78525682  91.27818777  47.02   0.33551277  0.939628451606   2.887      0
jxl:d1:6         20795  4595626    1.7679074   7.529  52.554   1.37131993  86.56306527  43.15   0.57029132  1.008222244600   2.520      0
jxl:d2:6         20795  2827975    1.0879036   7.786  53.118   2.45176829  78.33221870  39.51   0.97094780  1.056297572305   2.797      0
jxl:d4:6         20795  1708456    0.6572319   6.966  41.195   4.02716225  65.59488495  36.31   1.57116057  1.032616846768   2.750      0
jxl:d8:6         20795  1028977    0.3958408   7.171  43.237   6.44043500  46.99756946  33.43   2.47871579  0.981176721564   2.584      0
Aggregate:       20795  4424257    1.7019829   7.643  47.212   1.42632225  77.68787923  43.11   0.55865627  0.950823427558   3.303      0
```

**Review by jyrkialakuijala — APPROVED** [review]

**Pull request merged**
