### PR TITLE
Remove the current GdkPixbuf plugin

### PR DESCRIPTION
**Pull request by sboukortt**

### CODE REVIEW

**Review by veluca93 — APPROVED** [review]

**Comment by jonsneyers** [comment]
Can we first have an alternative implementation and then remove?

**Review by deymo — APPROVED** [review]

**Comment by deymo** [comment]
I'm ok to remove now

**Comment by xiota** [comment]
Could the headers be restored (from the FLIF version) and the plugin be sent upstream to the GTK folks?  It's only really useful when combined with their code anyway.

**Comment by deymo** [comment]
It is not a lot of work to write a new one from scratch anyway.

**Comment by veluca93** [comment]
I believe given #519 we don't need this anymore.

**Pull request closed without merging**
