### PR TITLE
Release v0.8.2

### PR DESCRIPTION
**Pull request by mo271**

### CODE REVIEW

**Review by veluca93 — DISMISSED** [review]

**Comment by mo271** [comment]
The CIFuzz / fuzzing fails because of https://github.com/libjxl/libjxl/pull/2427 and relatedly https://github.com/google/oss-fuzz/pull/10171.

We can't just cherry-pick those fixes to make the test pass, since they would require other jpegli-changes.
However, I think this workflow is not blocker. What do you think @veluca93 and @szabadka?

**Comment by szabadka** [comment]
I don't think it is a blocker. Ideally the code that builds the fuzzers should also be in the jxl repo and the ossfuzz should only reference one script that does everything, but it is probably too late to change that for this release.

**Comment by veluca93** [comment]
> I don't think it is a blocker. Ideally the code that builds the fuzzers should also be in the jxl repo and the ossfuzz should only reference one script that does everything, but it is probably too late to change that for this release.

+1, just submit :P

**Review by veluca93 — DISMISSED** [review]

**Comment by mo271** [comment]
ok, reverting to only having one cherry-pick, because I realized that fixing the MSYS2 / mingw32 tests would require at least 4 more cherry-picks...
I think it is cleaner to only have the more relevant fix here.

**Pull request merged**
