### PR TITLE
fix frame_settingsTest

### PR DESCRIPTION
**Pull request by mo271**

### CODE REVIEW

**Comment by mo271** [comment]
failing here for example: https://github.com/libjxl/libjxl/actions/runs/4927899421/jobs/8807677383

**Comment by mo271** [comment]
I having some flexibility in the test was needed after https://github.com/libjxl/libjxl/pull/1618, and apparently the amount of tolerance we have right now leads to flaky test behaviour, hence the update of the tolerance.

**Review by veluca93 — APPROVED** [review]
I'm a bit scared of the implications of this being necessary but sure...

**Comment by mo271** [comment]
> I'm a bit scared of the implications of this being necessary but sure...

Yeah, it is a bit peculiar, I don't have a better explanation...

**Pull request merged**
