### PR TITLE
Use the correct macro to enable memory limits in fuzz builds.

### PR DESCRIPTION
**Pull request by veluca93**

### CODE REVIEW

**Review by eustas — APPROVED** [review]

**Comment by eustas** [comment]
This will require changes in oss-fuzz projects as well. Including libvips.

**Comment by veluca93** [comment]
AFAIU that macro is enabled by default in oss-fuzz projects.

**Comment by eustas** [comment]
For honggfuzz as well?

**Comment by veluca93** [comment]
> For honggfuzz as well?

No idea - it's the recommended macro by LLVM's fuzzing guide though

**Review by sboukortt — APPROVED** [review]

**Pull request merged**
