### PR TITLE
fix RoundtripLosslessAnimation test

### PR DESCRIPTION
**Pull request by mo271**

### CODE REVIEW

**Comment by mo271** [comment]
see, https://github.com/libjxl/libjxl/actions/runs/5256709528/jobs/9498417869
Was this caused by https://github.com/libjxl/libjxl/pull/2523, @jonsneyers ?

**Comment by mo271** [comment]
I don't understand why it only fails in the Bazel test

**Comment by jonsneyers** [comment]
> see, https://github.com/libjxl/libjxl/actions/runs/5256709528/jobs/9498417869 Was this caused by #2523, @jonsneyers ?

I haven't checked but my guess would be yes. Lossless 
will be different when palette can be done (mostly better, I hope), so it could be this is an example of that. I wonder why it didn't fail earlier though — is this a test that is not in the PR CI?

**Comment by mo271** [comment]
I think it is in the PR CI when you add https://github.com/libjxl/libjxl/labels/CI%3Afull

**Review by jonsneyers — APPROVED** [review]

**Pull request merged**
