### PR TITLE
jpegli: optimize YCbCr base quant matrix with simplex search

### PR DESCRIPTION
**Pull request by szabadka**
Benchmark before (using jpegli's libjpeg.so)
```
Encoding      kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs
------------------------------------------------------------------------------------------------------------
jpeg:q85        13270  3476042    2.0955083   9.324  35.918   2.72852015   0.78030644  1.635138617422      0
jpeg:q90        13270  4506716    2.7168431   8.700  32.682   2.24054384   0.60948147  1.655865525274      0
jpeg:q95        13270  6338387    3.8210535   7.794  28.288   1.57034516   0.42314817  1.616871820730      0
```

Benchmark after:
```
Encoding      kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs
------------------------------------------------------------------------------------------------------------
jpeg:q85        13270  3123461    1.8829572   9.451  36.982   2.36939478   0.77342544  1.456327037747      0
jpeg:q90        13270  4038739    2.4347264   8.925  34.186   1.84759343   0.58653857  1.428060918036      0
jpeg:q95        13270  5925184    3.5719569   7.976  29.203   1.22262931   0.38715731  1.382909212412      0
```

### CODE REVIEW

**Comment by jonsneyers** [comment]
Be careful with overfitting for Butteraugli here. It could be a good idea to check ssimulacra2 and dssim results too, or even optimize for a mixture of metrics.

**Comment by jonsneyers** [comment]
PSNR increasing is somewhat reassuring, but ssimulacra2 increasing would be a kind of validation :)

**Comment by szabadka** [comment]
With ssimulacra2 the results are not that impressive, I did not plot it, but glancing over the two curves seem to align.

Before:
```
Encoding      kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2        pnorm       BPP*pnorm   Bugs
-------------------------------------------------------------------------------------------------------------------------
jpeg:q85        13270  3476042    2.0955083   3.084  12.435   2.72852015  85.22388490   0.78030644  1.635138617422      0
jpeg:q86        13270  3600853    2.1707498   3.324  12.457   2.84466934  85.96147905   0.75071686  1.629618434114      0
jpeg:q87        13270  3846317    2.3187261   3.318  13.437   2.53461552  87.26786912   0.70988172  1.646021254883      0
jpeg:q88        13270  3973516    2.3954071   2.993  11.721   2.48884010  87.72912956   0.68670768  1.644944458100      0
jpeg:q89        13270  4179810    2.5197701   3.114  12.839   2.41585612  88.83811364   0.65026649  1.638522031602      0
jpeg:q90        13270  4506716    2.7168431   3.087  12.233   2.24054384  90.06072583   0.60948147  1.655865525274      0
jpeg:q91        13270  4698889    2.8326933   2.807  12.001   2.11619473  91.05027869   0.58355606  1.653035339094      0
jpeg:q92        13270  4987690    3.0067950   3.011  11.414   1.92598557  91.87554123   0.54623133  1.642405629558      0
jpeg:q93        13270  5379441    3.2429595   3.062  11.930   1.94072545  92.92781606   0.51063253  1.655960577736      0
jpeg:q94        13270  5773186    3.4803259   3.069  10.793   1.78056836  94.51114464   0.47441801  1.651129306657      0
jpeg:q95        13270  6338387    3.8210535   2.950  10.272   1.57034516  95.77712552   0.42314817  1.616871820730      0
Aggregate:      13270  4533484    2.7329802   3.071  11.926   2.20063081  90.05092409   0.60104444  1.642642554943      0
```

After:
```
Encoding      kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2        pnorm       BPP*pnorm   Bugs
-------------------------------------------------------------------------------------------------------------------------
jpeg:q85        13270  3123461    1.8829572   3.270  14.081   2.36939478  83.26278722   0.77342544  1.456327037747      0
jpeg:q86        13270  3283725    1.9795713   2.991  14.625   2.30945301  84.21983553   0.73625973  1.457478624147      0
jpeg:q87        13270  3440923    2.0743370   3.240  13.356   2.17865801  85.24867527   0.69975474  1.451527172766      0
jpeg:q88        13270  3600599    2.1705966   3.236  12.520   2.10490155  86.01251216   0.66909472  1.452334748274      0
jpeg:q89        13270  3812055    2.2980715   3.087  12.676   2.13985419  87.06778023   0.63003914  1.447874953500      0
jpeg:q90        13270  4038739    2.4347264   3.122  13.778   1.84759343  88.24464368   0.58653857  1.428060918036      0
jpeg:q91        13270  4286713    2.5842158   2.978  11.939   1.62111247  89.40292951   0.55596468  1.436732700489      0
jpeg:q92        13270  4564545    2.7517049   2.968  12.668   1.52637219  90.44427429   0.51778464  1.424790537334      0
jpeg:q93        13270  4934402    2.9746707   2.992  12.407   1.54593706  91.69846052   0.47692591  1.418697543657      0
jpeg:q94        13270  5371016    3.2378805   2.833  12.229   1.36094320  93.37535406   0.43810030  1.418516403086      0
jpeg:q95        13270  5925184    3.5719569   2.956  12.201   1.22262931  94.99264196   0.38715731  1.382909212412      0
Aggregate:      13270  4133046    2.4915785   3.058  12.927   1.79712389  88.46854130   0.57551888  1.433950465403      0
```

**Comment by jonsneyers** [comment]
Does look like an improvement according to ssimulacra2 too. Perhaps we should make some script to compute the BD rate between two benchmark_xl outputs.

**Comment by jonsneyers** [comment]
What happens in the q70-84 range?

**Comment by szabadka** [comment]
Before:
```
Encoding      kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2        pnorm       BPP*pnorm   Bugs
-------------------------------------------------------------------------------------------------------------------------
jpeg:q70        13270  2219473    1.3379942   3.657  14.487   4.28571606  75.88128138   1.16787044  1.562603891727      0
jpeg:q71        13270  2283818    1.3767842   3.339  16.439   4.07089710  76.51952381   1.14127516  1.571289563704      0
jpeg:q72        13270  2333033    1.4064531   3.461  15.651   4.05626011  77.00756957   1.11704128  1.571066155124      0
jpeg:q73        13270  2396827    1.4449109   3.341  15.320   3.89110470  77.66657064   1.09060872  1.575832388687      0
jpeg:q74        13270  2451938    1.4781342   3.332  14.365   3.88654089  78.14784393   1.07284459  1.585808233749      0
jpeg:q75        13270  2506470    1.5110084   3.648  14.957   3.77717543  78.66599973   1.04806212  1.583630677245      0
jpeg:q76        13270  2589417    1.5610124   3.518  15.276   3.66709733  79.28679605   1.02022800  1.592588600372      0
jpeg:q77        13270  2641992    1.5927069   3.303  13.680   3.64256620  79.81632608   1.00234579  1.596443082426      0
jpeg:q78        13270  2726284    1.6435218   3.523  13.457   3.41842318  80.48600030   0.97232934  1.598044444731      0
jpeg:q79        13270  2831044    1.7066756   3.633  16.704   3.17060351  81.24908234   0.94201394  1.607712235906      0
jpeg:q80        13270  2890115    1.7422862   3.452  14.867   3.19422698  81.59807454   0.92539546  1.612303726935      0
jpeg:q81        13270  2994648    1.8053032   3.305  14.208   3.05283451  82.55226633   0.89063267  1.607862006437      0
jpeg:q82        13270  3115069    1.8778982   3.178  14.265   3.08145237  83.19933158   0.86246504  1.619621533805      0
jpeg:q83        13270  3189982    1.9230590   3.677  15.498   3.20958614  83.65374025   0.84150412  1.618262046323      0
jpeg:q84        13270  3366869    2.0296941   3.082  13.074   2.85605264  84.70528922   0.80261496  1.629062856122      0
Aggregate:      13270  2681405    1.6164665   3.425  14.783   3.52499632  79.98507791   0.98694035  1.595356030241      0
```

After:
```
Encoding      kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2        pnorm       BPP*pnorm   Bugs
-------------------------------------------------------------------------------------------------------------------------
jpeg:q70        13270  1988221    1.1985855   3.588  16.409   3.72467422  73.26008299   1.20877484  1.448820023383      0
jpeg:q71        13270  2041581    1.2307532   4.147  18.706   3.71326780  73.90036389   1.17980136  1.452044336600      0
jpeg:q72        13270  2090959    1.2605204   3.555  15.938   3.55086756  74.44083357   1.15200736  1.452128804807      0
jpeg:q73        13270  2146344    1.2939089   3.680  18.681   3.75958657  75.14756716   1.12537835  1.456137058516      0
jpeg:q74        13270  2196075    1.3238889   3.859  17.244   3.43980384  75.69122985   1.10207722  1.459027786189      0
jpeg:q75        13270  2251893    1.3575384   3.955  17.867   3.56745434  76.23876270   1.07243229  1.455868004711      0
jpeg:q76        13270  2316493    1.3964821   3.931  15.437   3.27775145  76.88905676   1.04329542  1.456943346896      0
jpeg:q77        13270  2380151    1.4348579   3.787  16.344   3.19377565  77.47694133   1.01823169  1.461017737651      0
jpeg:q78        13270  2451503    1.4778719   3.702  15.729   3.04156828  78.17807300   0.98774660  1.459762975450      0
jpeg:q79        13270  2538094    1.5300727   4.053  17.646   2.91462779  79.00242706   0.95530022  1.461678803107      0
jpeg:q80        13270  2607930    1.5721729   3.667  15.862   3.01959443  79.44380221   0.93114164  1.463915625285      0
jpeg:q81        13270  2704816    1.6305799   3.375  14.316   2.82410574  80.41408370   0.89617511  1.461285168986      0
jpeg:q82        13270  2798026    1.6867710   3.799  14.038   2.83588743  81.09134935   0.86715743  1.462695974750      0
jpeg:q83        13270  2889957    1.7421909   3.366  12.927   2.75129819  81.68678116   0.83818610  1.460280228151      0
jpeg:q84        13270  3022734    1.8222347   3.729  14.899   2.59719276  82.63177688   0.80108765  1.459769682129      0
Aggregate:      13270  2408657    1.4520423   3.740  16.052   3.19170087  77.64722958   1.00416195  1.458085609592      0
```

**Comment by jonsneyers** [comment]
Looks like a very big improvement in BA and a very small improvement according to ssimulacra2.

It would be interesting to visualize the change in the quant tables in some way to get an idea of what is changing (say a color-coded diff matrix where quantization constants that go up are in green and the ones that go down are in red, or something like that), to get a feel for what the overall change is, and perhaps to detect some anomalies in the change that could be caused by butteraugli weirdnesses...

**Review by jyrkialakuijala — APPROVED** [review]

**Comment by jyrkialakuijala** [comment]
Nothing is final in the code. Let's get this in as it looks like a likely nice improvement so that we can start to accumulate experience on this code.

**Pull request merged**
