### PR TITLE
Add "IrfanView" to supported image viewers list

### PR DESCRIPTION
**Pull request by nebenzhal**
noted that "IrfanView Plugins" needs to be installed and enabled by the user

### CODE REVIEW

**Comment by jonsneyers** [comment]
Any PR to this repo requires you to sign the CLA and add your name to AUTHORS. Sorry about the bureaucracy :)

**Comment by nebenzhal** [comment]
Done :)

**Comment by nebenzhal** [comment]
Ok now i'm actually done, really sorry for the separate authors PR, i'm new to this.

**Comment by jonsneyers** [comment]
No problem.
Two things:

- you have to keep AUTHORS alphabetically sorted :)
- the author check fails with `User nebenzhal <64442182+nebenzhal@users.noreply.github.com> not found, please add yourself to the AUTHORS file`, so I'm guessing the email address you used for the commits doesn't match the one you added. Something like this should fix that: `git commit --amend --author="Yonatan Nebenzhal <yonatan.nebenzhl@gmail.com>"` (and then `git push --force` again)

You may need to squash both commits before updating the author, which you should be able to do with `git rebase -i main` and then changing the second commit to `squash` instead of `pick`.

Sorry for making you jump through all those hoops :)

**Review by mo271 — APPROVED** [review]
Thank you for the pull request!

**Pull request merged**
