### PR TITLE
Hazard elimination: C++ enum class defs must parallel C API.

### PR DESCRIPTION
**Pull request by fischbacher**

### CODE REVIEW

**Comment by veluca93** [comment]
Couldn't we remove the C++ enum entirely?

**Comment by fischbacher** [comment]
Removing the C++ enums: Your call - it's more your code than mine, after all.

There might be some value in having proper a C++ enum class.

**Comment by veluca93** [comment]
> Removing the C++ enums: Your call - it's more your code than mine, after all.
> 
> There might be some value in having proper a C++ enum class.

@sboukortt do you know if the field visitors should still work with C enums? If so, I'd think it better to only stick with the C enums.

**Comment by sboukortt** [comment]
> > Removing the C++ enums: Your call - it's more your code than mine, after all.
> > There might be some value in having proper a C++ enum class.
> 
> @sboukortt do you know if the field visitors should still work with C enums? If so, I'd think it better to only stick with the C enums.

From what I can tell, they should, but the C++ side will still contain some duplication through the `EnumBits` functions that it needs to overload.

**Review by veluca93 — APPROVED** [review]

**Pull request merged**
