### PR TITLE
Removed warnings under Visual Studio (Windows)

### PR DESCRIPTION
**Pull request by sati32**
As requested in the issue.

### CODE REVIEW

**Comment by eustas** [comment]
Please use static_cast

**Comment by jonsneyers** [comment]
Also please sign the CLA and add your name to `AUTHORS`.

(btw why is the cla bot no longer commenting?)

**Comment by jonsneyers** [comment]
> We couldn't find a Contributor License Agreement (CLA) for some of the contributors shown below. All contributors listed must be covered under a CLA for this pull request to be merged.
>
> 📝 If you are not currently covered under a CLA, please visit https://cla.developers.google.com/. Once you've signed (or fixed any issues), please request a rescan from a repository manager.

**Comment by mo271** [comment]
> Also please sign the CLA and add your name to `AUTHORS`.
> 
> (btw why is the cla bot no longer commenting?)
AUTHORS is fine no, the CLA still missing. Don't know what is up with @googlebot ..

**Review by eustas — DISMISSED** [review]

**Comment by sati32** [comment]
sorry, but I don't know how to do this.
Since nothing happened here for a long time, I left this problem.

**Comment by mo271** [comment]
> sorry, but I don't know how to do this. Since nothing happened here for a long time, I left this problem.

Please visit https://cla.developers.google.com/. Once you've signed, follow the "New Contributors" link at the bottom of this page to update this check.

**Comment by mo271** [comment]
I think this can be merged now, @eustas?!

**Review by eustas — DISMISSED** [review]

**Comment by mo271** [comment]
> Still one c-cast remains, but ok. Going to fix it and other ~55 entries in one go afterwards (regex `[^fL]\(\w+_t\)[^,;:>)]`)

I removed the remaining c-cast, @eustas

**Pull request merged**
