### PR TITLE
Remove LCMS mutex

### LINKED ISSUE #53: Remove LCMS mutex
**Describe the bug**
We have a mutex in the LCMS color_management which can probably be removed after an update in LCMS. See https://github.com/libjxl/libjxl/pull/23#discussion_r641966901 for context.

### PR DESCRIPTION
**Pull request by kleisauke**
This is no longer required after commit https://github.com/mm2/Little-CMS/commit/a35bacde52e06aac4704db3e35ad434822938dc2, https://github.com/mm2/Little-CMS/commit/45a7fea828e1fbaca3c11d1110eec65890231fd8 and https://github.com/mm2/Little-CMS/commit/79e8395cd405daa9fc99d7ab154762718587887a.

Note that for the future possible enhancement [wg1/jpeg-xl#124](https://gitlab.com/wg1/jpeg-xl/-/issues/124) it might be necessary to raise the minimum required version of LCMS to 2.11 or later.

Resolves #53.

<details>
  <summary>TSAN results</summary>

Run with:
```bash
$ BUILD_DIR=build_tsan CC=clang-12 CXX=clang++-12 SKIP_TEST=1 ./ci.sh tsan -DJPEGXL_ENABLE_SKCMS=OFF
$ ./build_tsan/lib/tests/passes_test
```

Commit 7369cc15594aab3c56a17d84191ac47517f2d70d:
```
ThreadSanitizer: reported 8 warnings
(see tsan-lcms2.10.log for more details)
```

Commit d2ed28b8306a06b999620961ba6c242d9523f43e:
```
Running main() from ../third_party/googletest/googletest/src/gtest_main.cc
[==========] Running 11 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 11 tests from PassesTest
[ RUN      ] PassesTest.RoundtripSmallPasses
[       OK ] PassesTest.RoundtripSmallPasses (571 ms)
[ RUN      ] PassesTest.RoundtripUnalignedPasses
[       OK ] PassesTest.RoundtripUnalignedPasses (431 ms)
[ RUN      ] PassesTest.RoundtripMultiGroupPasses
[       OK ] PassesTest.RoundtripMultiGroupPasses (20999 ms)
[ RUN      ] PassesTest.RoundtripLargeFastPasses
[       OK ] PassesTest.RoundtripLargeFastPasses (6251 ms)
[ RUN      ] PassesTest.RoundtripProgressiveConsistent
[       OK ] PassesTest.RoundtripProgressiveConsistent (4399 ms)
[ RUN      ] PassesTest.AllDownsampleFeasible
[       OK ] PassesTest.AllDownsampleFeasible (4763 ms)
[ RUN      ] PassesTest.AllDownsampleFeasibleQProgressive
[       OK ] PassesTest.AllDownsampleFeasibleQProgressive (4823 ms)
[ RUN      ] PassesTest.ProgressiveDownsample2DegradesCorrectlyGrayscale
[       OK ] PassesTest.ProgressiveDownsample2DegradesCorrectlyGrayscale (11849 ms)
[ RUN      ] PassesTest.ProgressiveDownsample2DegradesCorrectly
[       OK ] PassesTest.ProgressiveDownsample2DegradesCorrectly (12903 ms)
[ RUN      ] PassesTest.NonProgressiveDCImage
[       OK ] PassesTest.NonProgressiveDCImage (5138 ms)
[ RUN      ] PassesTest.RoundtripSmallNoGaborishPasses
[       OK ] PassesTest.RoundtripSmallNoGaborishPasses (465 ms)
[----------] 11 tests from PassesTest (72592 ms total)

[----------] Global test environment tear-down
[==========] 11 tests from 1 test suite ran. (72592 ms total)
[  PASSED  ] 11 tests.
```

Attachments:
[tsan-lcms2.10.log](https://github.com/libjxl/libjxl/files/6584324/tsan-lcms2.10.log)
</details>

### CODE REVIEW

**Comment by veluca93** [comment]
If I understand correctly, this will fail compilation on systems that don't have a safe alternative to `gmtime`, right? Any clue what those systems are?

**Comment by kleisauke** [comment]
It will fallback to `gmtime` when neither `gmtime_r` nor `_gmtime64_s` (Windows specific) are available. AFAIK, most modern systems do have thread-safe alternatives available. Perhaps it would be better to guard `gmtime` with a global mutex in LCMS in case such alternative is missing?

**Comment by veluca93** [comment]
> It will fallback to `gmtime` when neither `gmtime_r` nor `_gmtime64_s` (Windows specific) are available. AFAIK, most modern systems do have thread-safe alternatives available. Perhaps it would be better to guard `gmtime` with a global mutex in LCMS in case such alternative is missing?

That sounds like a good idea - having a function that is thread unsafe on *some* systems seems like a good recipe for funny bugs...

By the way, cppreference mentions gmtime_s being a C11 function, I don't know if that'd be an option for LCMS (but it's different from the Windows version, because *of course* it is)

**Comment by deymo** [comment]
What's the oldest version of lcms that is required for this patch to work?

**Comment by kleisauke** [comment]
> That sounds like a good idea - having a function that is thread unsafe on _some_ systems seems like a good recipe for funny bugs...

A pull request has been made to fix this at https://github.com/mm2/Little-CMS/pull/264. I'll update the submodule once that lands.

> By the way, cppreference mentions gmtime_s being a C11 function, I don't know if that'd be an option for LCMS (but it's different from the Windows version, because _of course_ it is)

I think LCMS is still based on C99, so that probably wouldn't be an option.

> What's the oldest version of lcms that is required for this patch to work?

LCMS v2.11 or later to fix the data race in `cmsGetContext()`. The `gmtime` data race fixes are (unfortunately) not present in any release of LCMS. We might be able to inform the various distros to apply these, but I'm not sure if this could be done _without_ requesting a CVE ID via [MITRE's webform](https://cveform.mitre.org/) (I've no experience with that).

**Comment by kleisauke** [comment]
Commit https://github.com/mm2/Little-CMS/commit/79e8395cd405daa9fc99d7ab154762718587887a fixes it, so I updated the submodule to use that revision.

**Comment by jyrkialakuijala** [comment]
Is this safe? How are other users of LCMS dealing with it?

**Comment by kleisauke** [comment]
It is safe according to TSAN. The now closed https://github.com/mm2/Little-CMS/issues/170 issue contains some more details about this. Unfortunately, the `gmtime` fixes require an unreleased version of LCMS, I have updated this PR to clarify this.

libvips [has backported these](https://github.com/libvips/build-win64-mxe/blob/f5512e9c964a67c7b9d3fe133957d9e1a61365cd/build/patches/lcms-2-fixes.patch) and [this PR](https://github.com/libvips/build-win64-mxe/blob/f5512e9c964a67c7b9d3fe133957d9e1a61365cd/build/patches/libjxl-0.6-fixes.patch) within the Windows builds. I don't know if any other LCMS users have also backported this (or are using an unreleased version of LCMS).

IIUC, this code path is only used for encoding JXL images? The libvips fuzzers are currently fuzzing the [libjxl+lcms](https://github.com/google/oss-fuzz/blob/a21768ce6a5056d27f82b2f412c86261ad2dc8d0/projects/libvips/build.sh#L174) combination, but only for decoding JXL images, not yet for the [`jxlsave`](https://www.libvips.org/API/current/VipsForeignSave.html#vips-jxlsave) function. @jcupitt perhaps we should add an `jxlsave_buffer_fuzzer`?

**Comment by jcupitt** [comment]
Sure a JXL save fuzzer would be a good idea. I've made an issue so it's not forgotten.

**Comment by kleisauke** [comment]
Rebased, PTAL. The `gmtime` data race fixes are present in LCMS v2.13 (released 2 weeks ago).

**Review by jyrkialakuijala — APPROVED** [review]

**Pull request merged**
