### PR TITLE
allow decoding to u32

### PR DESCRIPTION
**Pull request by jonsneyers**
Fixes https://github.com/libjxl/libjxl/issues/1116

For some reason, the decode api didn't allow decoding to UINT32, while it actually works fine as far as I can tell (besides the fact that only the 24 msb will be useful, given that everything goes through float32 internally). Only the test_utils.h code for testing UINT32 decoding had some bugs, fixed those.

### CODE REVIEW

**Comment by jonsneyers** [comment]
An alternative solution is to deprecate UINT32 pixelformats, since the use case for it is not very clear, also considering that jxl does not actually support lossless uint32 encoding.

**Comment by jonsneyers** [comment]
Opinions please: the options are "implement uint32 in the api" or "deprecate uint32 in the api".

I don't have a strong preference myself: keeping it could be nice for applications that don't want to deal with float, or for a future where we no longer necessarily convert modular to float before returning it, so we could support up to 31-bit integer (which fits in uint32 but not in float32). Deprecating it is currently no big loss since float32 is available as an alternative and is what is used internally anyway, and it is confusing to have a uint32 pixel_format when the bitstream itself doesn't actually support uint32 samples.

**Comment by jonsneyers** [comment]
(pinging @jyrkialakuijala @veluca93  @sboukortt @eustas @mo271 @fischbacher for opinions on this)

**Comment by malaterre** [comment]
Just for reference, here is what openjpeg states for 32bits input:

```
% opj_decompress -i input32.j2k -o output.pgx

[INFO] Start to read j2k main header (0).
[ERROR] Invalid values for comp = 0 : prec=32 (should be between 1 and 38 according to the JPEG2000 norm. OpenJpeg only supports up to 31)
[ERROR] Marker handler function failed to read the marker segment
ERROR -> opj_decompress: failed to read the header
```

**Comment by jonsneyers** [comment]
Closing in favor of https://github.com/libjxl/libjxl/pull/1337

**Pull request closed without merging**
