### PR TITLE
Instruct EMCC to link libpng.

### PR DESCRIPTION
**Pull request by eustas**

### CODE REVIEW

**Comment by jonsneyers** [comment]
Does this also cause it to have JPEGXL_ENABLE_APNG set?

**Review by veluca93 — APPROVED** [review]

**Comment by veluca93** [comment]
> Does this also cause it to have JPEGXL_ENABLE_APNG set?

I don't see how that could happen :)

**Comment by eustas** [comment]
Nope, it is just a request to emcc to link "port" library (if necessary).

**Comment by jonsneyers** [comment]
But it will never actually do anything then in terms of making the wasm builds of cjxl/djxl/benchmark_xl support png? Or will it?

**Pull request merged**
