### PR TITLE
add minor versions to changelog

### PR DESCRIPTION
**Pull request by mo271**

### CODE REVIEW

**Review by eustas — APPROVED** [review]

**Comment by eustas** [comment]
#3201? That is OOB

**Comment by mo271** [comment]
Here I'm just copying what we had in the individual release note.

**Comment by wwinniww** [comment]
Hello
Is the year for the last two entries correct? Should it be 2024 instead?

**Comment by mo271** [comment]
> Hello Is the year for the last two entries correct? Should it be 2024 instead?

Yes, thanks, I will fix it...

**Pull request merged**
