### PR TITLE
Add an option to generate noise of more photorealistic intensity

### PR DESCRIPTION
**Pull request by sboukortt**
For now, whenever the parameter is set, it is used as-is without
attenuation for lower distances.

The sparseness of the LUT at the bottom end makes this not quite as
fine-grained (no pun intended) as would be ideal but it’s a start.

### CODE REVIEW

**Review by veluca93 — COMMENTED** [review]
Test please? :)

**Comment by sboukortt** [comment]
> Test please? :)

What sort of test do you think would be appropriate? Maybe just a few LUTs for a few input values?

**Comment by veluca93** [comment]
Yes, and/or roundtrip tests

**Comment by sboukortt** [comment]
How is this?

**Review by veluca93 — APPROVED** [review]

**Pull request merged**
