### PR TITLE
Allow adding prefix for pkg-config

### PR DESCRIPTION
**Pull request by mo271**
This fixes https://github.com/libjxl/libjxl/issues/1400.

### CODE REVIEW

**Comment by mo271** [comment]
I'm not sure if this is the correct way of fixing this.

**Comment by mo271** [comment]
Could you take a look, @alexshpilkin?!

**Comment by alexshpilkin** [comment]
Yes, I’m sorry @mo271. I’ve been trying to get the existing Nixpkgs recipe to build this version, but it isn’t as straightforward as I’ve hoped because some change since 0.6.1 seems to mess with LD_LIBRARY_PATH and cause the tests to fail to run because they can’t find libgmock. I’ll have another look today.

**Comment by mo271** [comment]
> Yes, I’m sorry @mo271. I’ve been trying to get the existing Nixpkgs recipe to build this version, but it isn’t as straightforward as I’ve hoped because some change since 0.6.1 seems to mess with LD_LIBRARY_PATH and cause the tests to fail to run because they can’t find libgmock. I’ll have another look today.

Cool, thanks! Perhaps dissecting it would help; might have been this change: https://github.com/libjxl/libjxl/pull/575?!

**Comment by alexshpilkin** [comment]
Neither of those is it, sorry, and Git (2.36.0)’s submodule support is so horribly broken, it seems, that it can’t even switch from this PR’s branch to the tag for 0.6.1, let alone bisect between them. I give up, I’ll leave figuring out how to build the eventual version 0.7 to the actual Nixpkgs maintainer.

That said, I did get the build to proceed far enough to generate the .pc files, and those look fine to me, so if this PR works in your more conventional environment it should be OK to merge. Thank you for the quick response, and I apologize for the confusion about who was representing what in the issue discussion.

**Pull request merged**
